export const metadata = {
	title: 'Layout Next.js',
	description: 'Generated by Next.js',
}
import Menu from './common/components/Menu'
import './styles/global.scss'

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Menu />
				<div className='main-container'>{children}</div>
			</body>
		</html>
	)
}
